//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RiskyPlaceTracker
{
    using System;
    using System.Collections.Generic;
    
    public partial class RD_Reports
    {
        public int ReportId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string Photo { get; set; }
        public Nullable<int> AddedBy { get; set; }
        public string AddedByName { get; set; }
        public Nullable<System.DateTime> AddedOn { get; set; }
    }
}
